server:
  port: 80
spring:
  profiles:
    active: dev
  redis:
    host: 127.0.0.1
    port: 6379
    password: redis@lsz #密码（默认为空）
    lettuce: # 这里标明使用lettuce配置
      pool:
        max-active: 8   #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1  #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 5     #连接池中的最大空闲连接
        min-idle: 2     #连接池中的最小空闲连接
    timeout: 1000     #连接超时时间（毫秒）
  application:
    name: application-paltfrom
  mvc:
    throw-exception-if-no-handler-found: true #出现错误时, 直接抛出异常 全局异常处理404
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/lsz002?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      initial-size: 5
      max-active: 200
      min-idle: 5
      max-wait: 1000
      pool-prepared-statements: false
      test-on-borrow: true
      test-on-return: false
      filter: wall,log4j,stat
  resources:
    add-mappings: false #关闭工程中的资源文件建立映射 全局异常处理404
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml
hibernate:
  validator:
    fail_fast: false # true-快速失败返回模式    false-普通模式

