package com.echo.drools.dto
import com.jx.drools.application.entity.User
import com.jx.drools.application.util.Valid
dialect "java"

rule "address eq beijing"
    when
        $user: User(address == "北京")
    then
         Valid.validUser($user);
         System.out.println($user.getName() + "是个北漂");
         System.out.println($user.getName() + "---123-");
    end

rule "address eq shanghai"
    when
        $user: User(address == "上海")
    then
         System.out.println($user.getName() + "是个上漂");
    end